### ISSUE TITLE
Linux Install Instructions

### ISSUE THREAD

**Issue by John-Whitehead** [a-student/SvgToVectorDrawableConverter#29]
I may be missing something simple here, but I am trying to install on Linux - Fedora 28 and the source file does not contain a makefile, exe, or any build instructions.

What am I missing here that I need to do to get this app running?  I have a lot of SVG files to convert and would rather use this over the web version or Android Studio.

**Comment by a-student** [comment]
You need to [download](https://github.com/a-student/SvgToVectorDrawableConverter/releases/latest) and unpack the converter, then follow [these instructions](https://github.com/a-student/SvgToVectorDrawableConverter#running-on-linux). Instead of `apt-get` you should use `dnf` package manager in Fedora.
Alternatively, you can try [the docker container](https://github.com/a-student/SvgToVectorDrawableConverter#running-in-docker). Search the internet on how to install and use Docker in Fedora.

**Comment by John-Whitehead** [comment]
Thanks, that did the trick.
