### ISSUE TITLE
OSX: Inkscape app was not found in the path '/usr/bin/inkscape'

### ISSUE THREAD

**Issue by cperry-gpsw** [a-student/SvgToVectorDrawableConverter#8]
I have installed inkscape on Mac OS X via home-brew. apt-get was not an option for me. Inkscape is definitely installed, but when I run 

``` bash
mono ~/Desktop/SvgToVectorDrawableConverter_v1/svg2vd.exe --fix-fill-type -i \*
```

I get 

``` bash
Inkscape app was not found in the path '/usr/bin/inkscape'. Please download it from https://inkscape.org/en/download and install it on your system.
```

inkscape is in `/usr/local/bin` not `/usr/bin`

**Comment by vectrawr** [comment]
You can use --inkscape /usr/local/bin/inkscape. It still does not work though. Why is it required now?

**Comment by vectrawr** [comment]
hmm actually according to this diff it looks for Inkscape.app instead of the brew inkscape. However it did not function with Inkscape.app either.

**Comment by vectrawr** [comment]
ok I got it working:

 mono svg2vd.exe -i ../dir_of_svgs/ -o ../ --fix-fill-type --inkscape /Applications/Inkscape.app/Contents/Resources/bin/inkscape

So I guess that automatic finding of Inkscape.app is what is broken. brew inkscape appears to not work with both 1.2 and 1.1, which is weird because that one doesn't have the weird monitor issues Inkscape.app has.

**Comment by a-student** [comment]
Thanks for the report! The bug fixed, please, download the latest version of the converter.
